name: Build and Deploy

on:
  push:
    branches:
      - main 
      
jobs:
  Build:
    name: "Build Docker Image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to docker
        run: |
          docker login -u anefu --password ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Docker Tag
        run: |
          echo "TAG=$GITHUB_REF_NAME-${GITHUB_SHA::5}" >> $GITHUB_ENV

      # - name: Build Image
      #   run: |
      #     docker build -t "anefu/k8s-python:${{ env.TAG }}" .

      # - name: Push image
      #   run:
      #       docker push "anefu/k8s-python:${{ env.TAG }}"

  Deploy:
    name: "Helm Deploy"
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set New Image Tag
        run: |
          echo ${{ env.TAG }}
          sed -i -e 's|{{TAG}}|${{ env.TAG }}|g' k8s-python/values.yaml
          cat k8s-python/values.yaml
